--update data-----------------
CREATE OR REPLACE PACKAGE UPDATE_DATABASE AS
END UPDATE_DATABASE;
/
CREATE OR REPLACE PACKAGE BODY UPDATE_DATABASE AS
END UPDATE_DATABASE;

--add row------------------
CREATE OR REPLACE PACKAGE ADD_TO_DATABASE AS
END ADD_TO_DATABASE;
/
CREATE OR REPLACE PACKAGE BODY ADD_TO_DATABASE AS
END ADD_TO_DATABASE;
--delete row package---------
CREATE OR REPLACE PACKAGE DELETE_FROM_DATABSE AS
END DELETE_FROM_DATABSE;
/
CREATE OR REPLACE PACKAGE BODY DELETE_FROM_DATABSE AS
END DELETE_FROM_DATABSE;