--update data-----------------
CREATE OR REPLACE PACKAGE COURSES_PACKAGE AS
END COURSES_PACKAGE;
/
CREATE OR REPLACE PACKAGE BODY COURSES_PACKAGE AS
END COURSES_PACKAGE;
/
--add row------------------
CREATE OR REPLACE PACKAGE COMPETENCIES_PACKAGE AS
END COMPETENCIES_PACKAGE;
/
CREATE OR REPLACE PACKAGE BODY COMPETENCIES_PACKAGE AS
END COMPETENCIES_PACKAGE;
/
--delete row package---------
CREATE OR REPLACE PACKAGE CC_BRIDGE_PACKAGE AS
END CC_BRIDGE_PACKAGE;
/
CREATE OR REPLACE PACKAGE BODY CC_BRIDGE_PACKAGE AS
END CC_BRIDGE_PACKAGE;
/