--Drop package--------------
DROP PACKAGE UPDATE_DATABASE;
DROP PACKAGE ADD_TO_DATABASE;
DROP PACKAGE DELETE_FROM_DATABSE;

--DROP TABLE------------------
DROP TABLE element_course;
DROP TABLE elements_of_competency;
DROP TABLE dawson_courses;
DROP TABLE term_seasons;
DROP TABLE seasons;
DROP TABLE educations;
DROP TABLE COMPETENCIES;

--DROP TYPE----------------
DROP TYPE COURSE_TYP;
DROP TYPE TERM_TYP;
DROP TYPE SEASON_TYP;

